### PR TITLE
Adding open ai embedding support.

### PR DESCRIPTION
**Pull request by pritam1984314**
We have tested changes for both tfidf and open ai embeddings. Both results look similar.
For open ai vectoriser we need OpenAI key. Follows below link that explain best practices regarding open ai key safety.
https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

Please let me know any changes/fixes need to do from my side if I missed.

Thanks,
Pritam

### CODE REVIEW

**Comment by yogeshhk** [comment]
Queries:
- As 'langchain' is used, any changes in environment.yml?
- in faqengine.py, at around lines 60 to 74 we try to get subset of questions matching the class or category of question, then from line 80 onward, cosine similarity is checked within the subset and not whole embedding set like done by` cos_sims = cosine_similarity(self.doc_emb, t_usr_array)`
- Rest of the file changes look ok

**Comment by pritam1984314** [comment]
> Queries:
> 
> * As 'langchain' is used, any changes in environment.yml?
I have added langchain and openai dependencies, working at local environment. please let me know if anything I miss here.
> * in faqengine.py, at around lines 60 to 74 we try to get subset of questions matching the class or category of question, then from line 80 onward, cosine similarity is checked within the subset and not whole embedding set like done by` cos_sims = cosine_similarity(self.doc_emb, t_usr_array)`

For loop approach gives problem when we run with openai embeddings, it took more than 2 min to respond for medium complex query. In new approach, we leverage pandas data frame to solve our filtering problem. I have test with 'tiff','openai' and 'space' embeddings with above solutions.
> * Rest of the file changes look ok

Please let me know if any problem still persist with proposed solution.

**Comment by yogeshhk** [comment]
Code is looking fine to me.. @pritam1984314

**Comment by pritam1984314** [comment]
Created other cleaner PR for changes present in this PR.
Closing this PR

**Pull request closed without merging**
